name: Check-in tests

on:
  push:
    branches:
      - 'main'
      - 'releases-**'
  pull_request:
  workflow_dispatch:

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  webapp-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: npm ci
      run: cd webapp && npm ci

    - name: Lint webapp
      run: cd webapp && npm run check

    - name: Type check webapp
      run: cd webapp && npm run check-types

  server-test:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: go.mod

    - name: Build server
      run: make server

    - name: set up golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/v1.64.8/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.64.8

    - name: Lint server
      run: make server-lint
